# Generated by Django 5.2.3 on 2025-06-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='memories/')),
                ('link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon_class', models.CharField(help_text="e.g., 'devicon-javascript-plain'", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(help_text="e.g., 'fab fa-twitter'", max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='linkedin_url',
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='languages_spoken',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='my_goals',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='link_code',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='link_live',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='skills',
            field=models.ManyToManyField(blank=True, to='content.skill'),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='social_links',
            field=models.ManyToManyField(blank=True, to='content.sociallink'),
        ),
    ]
