# Generated by Django 5.2.3 on 2025-07-06 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_personalinfo_profile_photo_remove_skill_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='image_url',
            new_name='image',
        ),
    ]
