# Generated by Django 5.2.3 on 2025-06-26 09:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_memory_skill_sociallink_remove_personalinfo_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='link_code',
        ),
        migrations.RemoveField(
            model_name='project',
            name='link_live',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='icon_class',
        ),
        migrations.AddField(
            model_name='memory',
            name='date_of_memory',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='project_url',
            field=models.URLField(blank=True, help_text='The main link for your project (Live Demo or Source Code).', null=True),
        ),
        migrations.AlterField(
            model_name='memory',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon_class',
            field=models.CharField(help_text="Find the class name at devicon.dev. e.g., 'devicon-python-plain'", max_length=100),
        ),
    ]
