# Generated by Django 5.2.3 on 2025-06-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_project_link_code_remove_project_link_live_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_url',
            field=models.URLField(blank=True, help_text='The main link for your project (e.g., Live Demo or GitHub).', null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon_class',
            field=models.CharField(help_text="Find the class name at devicon.dev. Example: 'devicon-python-plain'", max_length=100),
        ),
    ]
