# Generated by Django 5.2.3 on 2025-06-26 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_project_project_url_alter_skill_icon_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='image',
        ),
        migrations.CreateModel(
            name='MemoryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='memories/')),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='content.memory')),
            ],
        ),
    ]
