# Generated by Django 5.2.3 on 2025-06-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_remove_memory_image_memoryphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='image',
            field=models.ImageField(blank=True, help_text="(Optional) Upload a custom image if you don't use an icon class.", null=True, upload_to='skill_icons/'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon_class',
            field=models.CharField(blank=True, help_text="(Optional) Find the class name at devicon.dev. Example: 'devicon-python-plain'", max_length=100, null=True),
        ),
    ]
