# Generated by Django 5.2.3 on 2025-07-02 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_memoryphoto_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalinfo',
            options={'verbose_name_plural': 'Personal Info'},
        ),
        migrations.RemoveField(
            model_name='memoryphoto',
            name='image',
        ),
        migrations.AddField(
            model_name='memoryphoto',
            name='image_url',
            field=models.URLField(default='', help_text="Paste the direct URL of the memory photo. For Google Photos: \n1. Open the photo. \n2. Click Share -> Create Link. \n3. Open the new link in a new tab. \n4. Right-click the image and select 'Copy Image Address'. \nPaste that link here. It should start with 'lh3.googleusercontent.com'.", max_length=500, verbose_name='Direct Image URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='memories',
            field=models.ManyToManyField(blank=True, to='content.memory'),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='projects',
            field=models.ManyToManyField(blank=True, to='content.project'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='profile_photo',
            field=models.URLField(blank=True, help_text="Paste the direct URL to your profile photo. For Google Photos: \n1. Open the photo. \n2. Click Share -> Create Link. \n3. Open the new link in a new tab. \n4. Right-click the image and select 'Copy Image Address'. \nPaste that link here. It should start with 'lh3.googleusercontent.com'.", max_length=500, null=True, verbose_name='Profile Photo URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_url',
            field=models.URLField(blank=True, help_text='The main link for your project (e.g., Live Demo or GitHub).', null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon_class',
            field=models.CharField(blank=True, help_text="Optional. Find class at devicon.dev. E.g., 'devicon-python-plain'", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.URLField(blank=True, help_text="Optional. Paste a direct image URL. For Google Photos: \n1. Open the photo. \n2. Click Share -> Create Link. \n3. Open the new link in a new tab. \n4. Right-click the image and select 'Copy Image Address'. \nPaste that link here. It should start with 'lh3.googleusercontent.com'.", max_length=500, null=True),
        ),
    ]
