# Generated by Django 4.2.7 on 2025-06-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_memoryphoto_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoryphoto',
            name='image',
            field=models.ImageField(upload_to='memories/'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload custom skill icon.', null=True, upload_to='skill_icons/'),
        ),
    ]
