"""
Django settings for portfolio_project project.
Generated by 'django-admin startproject' using Django 4.2.
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- SECURITY: Load SECRET_KEY from environment variables ---
# This is crucial for production. Never leave your secret key in the code.
SECRET_KEY = os.environ.get('SECRET_KEY')

# --- DEBUG SETTING based on Render Environment ---
# DEBUG will be False on Render (production) and True otherwise (local dev)
DEBUG = os.environ.get('RENDER') != 'true'

# --- ALLOWED_HOSTS for Render and your custom domain ---
ALLOWED_HOSTS = []
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# Add your custom domains here
ALLOWED_HOSTS.extend(['satyampote.tech', 'www.satyampote.tech'])


# --- Application definition ---
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic', # For serving static files in production
    'django.contrib.staticfiles',
    'content',      # Your content app
    'corsheaders',  # The CORS app
]

# --- Middleware Configuration (with Whitenoise and CORS) ---
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # Whitenoise must be high up
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware', # Placed correctly before CommonMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'portfolio_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'portfolio_project.wsgi.application'

# --- Database configured for Render ---
DATABASES = {
    'default': dj_database_url.config(
        # Use a local SQLite database if DATABASE_URL is not set
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}

# --- Password validation ---
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# --- Internationalization ---
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# --- Static files (CSS, JavaScript, Images) for Production ---
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# --- Default primary key field type ---
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =========================================================================
#  CORS & CSRF SETTINGS - This is the key to connecting your services
# =========================================================================

# Tells Django which frontend origins are allowed to make API requests.
CORS_ALLOWED_ORIGINS = [
    "https://satyampote.tech",         # Your live frontend URL
    "https://*.onrender.com",          # Allows Render's preview URLs
    "http://127.0.0.1:5500",           # For local testing
    "http://localhost:3000",           # For local testing with React/Vue
]

# Tells Django which domains are safe for POST/PUT/DELETE requests.
CSRF_TRUSTED_ORIGINS = [
    "https://satyampote.tech",         # Your live frontend URL
    "https://*.onrender.com",          # Allows Render's preview URLs
]