<<<<<<< HEAD
# settings.py
=======
"""
Django settings for portfolio_project project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
>>>>>>> parent of 0bbc509 (Refactor portfolio backend and frontend integration)

from pathlib import Path
import os
import dj_database_url


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

<<<<<<< HEAD
SECRET_KEY = '253-l6vqf+mq4uhinb5pj^aq4(&*se@gxsbb@hlu6yc0h2^v3c'
DEBUG = True

ALLOWED_HOSTS = [
    'satyampote.tech',
    'www.satyampote.tech',
    'personal-dashboard-backend-dxrt.onrender.com',
    'satyam-portfolio-backend.onrender.com'
]
=======

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '253-l6vqf+mq4uhinb5pj^aq4(&*se@gxsbb@hlu6yc0h2^v3c' # Replace with your key

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = []
>>>>>>> parent of 0bbc509 (Refactor portfolio backend and frontend integration)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'content',      # Your content app
    'corsheaders',  # The CORS app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # ✅ Crucial for serving static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware', # Must be before CommonMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'djanzgo.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'portfolio_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # <-- Point to your templates directory
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'portfolio_project.wsgi.application'

<<<<<<< HEAD
=======

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

>>>>>>> parent of 0bbc509 (Refactor portfolio backend and frontend integration)
DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}

<<<<<<< HEAD
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

=======


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

>>>>>>> parent of 0bbc509 (Refactor portfolio backend and frontend integration)
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

<<<<<<< HEAD
# ✅ Static files (CSS, JS, Images)
STATIC_URL = '/static/'
# STATIC_ROOT is where collectstatic gathers ALL static files from various locations.
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# ✅ Add your frontend directory to STATICFILES_DIRS
# This tells Django to also look for static files inside the 'frontend' folder.
STATICFILES_DIRS = [
    BASE_DIR / 'frontend',
]

# ✅ WhiteNoise configuration
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# ✅ Media files (optional)
=======

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

>>>>>>> parent of 0bbc509 (Refactor portfolio backend and frontend integration)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

<<<<<<< HEAD
# ✅ CORS
=======

# --- CORS SETTINGS ---
# This is the most important part for connecting the frontend.
# It tells Django which frontend addresses are allowed to make requests.

ALLOWED_HOSTS = [
    'satyampote.tech',                      # Your frontend domain
    'www.satyampote.tech',                  # Your frontend domain with www
    'personal-dashboard-backend-dxrt.onrender.com', # Your LIVE backend domain
    'satyam-portfolio-backend.onrender.com' # Adding this one too, just in case
]

>>>>>>> parent of 0bbc509 (Refactor portfolio backend and frontend integration)
CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:5500",
    "http://localhost:5500",
    "https://satyampote.tech", # Your live frontend URL (using https)
]